name: "Dantunkura Gallery App"

on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET Core SDK 
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100

    - name: Restore
      run: dotnet restore  

    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish DantunkuraGallery.csproj --no-build -c Release -o release
           
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot


