name: "Dantunkura Gallery App"

on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 5 SDK 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.1
    
    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish --no-build -c Release -o release

    - name: Change default route
      run: sed -i 's/base href="\/" \/>/<base href="\/DantunkuraGallery\/" \/>/g' release/wwwroot/index.html
        
   - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot


