name: "Dantunkura Gallery App"

env:
  PUBLISH_DIR: bin/Release/netstandard2.1/publish/wwwroot

on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET Core SDK 
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100

    - name: Restore
      run: dotnet restore  

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish
      run: dotnet publish --no-build -c Release -o release

     - name: Rewrite base href
      uses: DantunkuraGallery/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /DantunkuraGallery/
           
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


